### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by sarina** [openedx/wg-marketing#1]
Test for board addition

**Comment by NicoleKessler** [comment]
@sarina can you give me access so that I can add/create issues? 
Also it would be nice to have a columns called "Backlog" and another one called "Meetings"

**Comment by sarina** [comment]
@NicoleKessler You can add/create issues right now! Please see https://openedx.atlassian.net/wiki/spaces/COMM/pages/3734241436/GitHub+Projects+Issues+A+Primer
